// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN222_Group2_Assignment1.Data;

#nullable disable

namespace PRN222_Group2_Assignment1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812035447_AddDocumentPipeline")]
    partial class AddDocumentPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "leader@chatbot.edu.vn",
                            FullName = "Subject Leader",
                            Password = "leader@123",
                            Role = "SubjectLeader"
                        });
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterNumber = 1,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 1,
                            Summary = "DbContext, Migration, Lazy Loading, Indexing, and Repository Pattern",
                            Title = "Chapter 1: Entity Framework Core & Data Architecture"
                        },
                        new
                        {
                            Id = 2,
                            ChapterNumber = 2,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 1,
                            Summary = "Tasks, Async/Await, Task.WhenAll, Thread Pooling, and Concurrency Controls",
                            Title = "Chapter 2: Async & Parallel Programming in C#"
                        },
                        new
                        {
                            Id = 3,
                            ChapterNumber = 3,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = 1,
                            Summary = "Text Extraction, Chunking Strategies, Vector Embeddings, and Retrieval Augmented Generation",
                            Title = "Chapter 3: AI Document Processing & RAG Integration"
                        });
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            ChunkCount = 4,
                            ContentHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                            FileExtension = "pdf",
                            FileName = "EFCore_BestPractices_PRN222.pdf",
                            FileSizeBytes = 2458000L,
                            IndexedAt = new DateTime(2025, 1, 10, 8, 32, 0, 0, DateTimeKind.Utc),
                            MimeType = "application/pdf",
                            Status = "Ready",
                            StoragePath = "uploads/prn222/EFCore_BestPractices_PRN222.pdf",
                            SubjectId = 1,
                            Title = "EF Core 8 High Performance & Best Practices Guide",
                            UploadedAt = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Utc),
                            UploadedById = 1
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 2,
                            ChunkCount = 3,
                            ContentHash = "8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
                            FileExtension = "pptx",
                            FileName = "Async_Await_Mastery.pptx",
                            FileSizeBytes = 5120000L,
                            IndexedAt = new DateTime(2025, 1, 12, 14, 16, 30, 0, DateTimeKind.Utc),
                            MimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            Status = "Ready",
                            StoragePath = "uploads/prn222/Async_Await_Mastery.pptx",
                            SubjectId = 1,
                            Title = "C# Async Await Deep Dive Lecture Slides",
                            UploadedAt = new DateTime(2025, 1, 12, 14, 15, 0, 0, DateTimeKind.Utc),
                            UploadedById = 1
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 3,
                            ChunkCount = 3,
                            ContentHash = "a4567223bfe70911228834900a01299dfa89110298a0011bbcd001299ff01234",
                            FileExtension = "docx",
                            FileName = "RAG_Chunking_Spec.docx",
                            FileSizeBytes = 1280000L,
                            IndexedAt = new DateTime(2025, 1, 15, 10, 2, 10, 0, DateTimeKind.Utc),
                            MimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            Status = "Ready",
                            StoragePath = "uploads/prn222/RAG_Chunking_Spec.docx",
                            SubjectId = 1,
                            Title = "RAG Architecture & Semantic Chunking Specification",
                            UploadedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            UploadedById = 1
                        });
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("HasEmbedding")
                        .HasColumnType("bit");

                    b.Property<string>("Heading")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChunkIndex = 1,
                            Content = "DbContext in Entity Framework Core is designed to be short-lived. Always use AddDbContext with Scoped lifetime in ASP.NET Core web applications.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2747),
                            DocumentId = 1,
                            HasEmbedding = true,
                            Heading = "1. DbContext Lifecycle",
                            PageNumber = 1,
                            TokenCount = 120
                        },
                        new
                        {
                            Id = 2,
                            ChunkIndex = 2,
                            Content = "For read-only queries, calling AsNoTracking() avoids change tracker overhead, boosting performance by up to 30% for large data retrieval.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2749),
                            DocumentId = 1,
                            HasEmbedding = true,
                            Heading = "2. AsNoTracking Query Optimization",
                            PageNumber = 3,
                            TokenCount = 145
                        },
                        new
                        {
                            Id = 3,
                            ChunkIndex = 3,
                            Content = "Ensure foreign keys and frequently filtered columns are indexed in EF Core using HasIndex() in OnModelCreating.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2750),
                            DocumentId = 1,
                            HasEmbedding = true,
                            Heading = "3. Explicit Indexing on Foreign Keys",
                            PageNumber = 5,
                            TokenCount = 110
                        },
                        new
                        {
                            Id = 4,
                            ChunkIndex = 4,
                            Content = "Use EF.CompileAsyncQuery for hot paths to bypass query expression tree parsing overhead.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2751),
                            DocumentId = 1,
                            HasEmbedding = true,
                            Heading = "4. Compiled Queries",
                            PageNumber = 8,
                            TokenCount = 95
                        },
                        new
                        {
                            Id = 5,
                            ChunkIndex = 1,
                            Content = "Async methods yield control back to the calling thread when awaiting an incomplete Task, preventing UI or HTTP worker thread blocking.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2752),
                            DocumentId = 2,
                            HasEmbedding = true,
                            Heading = "Slide 2: Thread Pool & Synchronization Context",
                            PageNumber = 2,
                            TokenCount = 130
                        },
                        new
                        {
                            Id = 6,
                            ChunkIndex = 2,
                            Content = "Async void should only be used for event handlers. Returning Task allows exception propagation and proper async orchestration.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2755),
                            DocumentId = 2,
                            HasEmbedding = true,
                            Heading = "Slide 5: Avoid Async Void",
                            PageNumber = 5,
                            TokenCount = 105
                        },
                        new
                        {
                            Id = 7,
                            ChunkIndex = 3,
                            Content = "Execute independent HTTP or I/O bound requests concurrently using Task.WhenAll to achieve high throughput.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2756),
                            DocumentId = 2,
                            HasEmbedding = true,
                            Heading = "Slide 9: Parallel Processing with Task.WhenAll",
                            PageNumber = 9,
                            TokenCount = 125
                        },
                        new
                        {
                            Id = 8,
                            ChunkIndex = 1,
                            Content = "Semantic chunking splits text at logical structural boundaries such as headings, paragraphs, and lists, preserving original context.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2757),
                            DocumentId = 3,
                            HasEmbedding = true,
                            Heading = "Section 1: Semantic Chunking Strategy",
                            PageNumber = 1,
                            TokenCount = 160
                        },
                        new
                        {
                            Id = 9,
                            ChunkIndex = 2,
                            Content = "Including a 100-token sliding window overlap between adjacent chunks prevents information loss at chunk boundaries during retrieval.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2758),
                            DocumentId = 3,
                            HasEmbedding = true,
                            Heading = "Section 2: Sliding Window & Overlap",
                            PageNumber = 2,
                            TokenCount = 150
                        },
                        new
                        {
                            Id = 10,
                            ChunkIndex = 3,
                            Content = "Generated embeddings are stored alongside chunk index and metadata, allowing fast cosine similarity search in the RAG retrieval pipeline.",
                            CreatedAt = new DateTime(2026, 8, 12, 3, 54, 46, 824, DateTimeKind.Utc).AddTicks(2760),
                            DocumentId = 3,
                            HasEmbedding = true,
                            Heading = "Section 3: Embedding Vector Storage",
                            PageNumber = 4,
                            TokenCount = 140
                        });
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRN222",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced C# .NET Core MVC, Entity Framework Core, Real-time Web Apps, and AI Integrations.",
                            Name = "Enterprise Web Application Development"
                        });
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Chapter", b =>
                {
                    b.HasOne("PRN222_Group2_Assignment1.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Document", b =>
                {
                    b.HasOne("PRN222_Group2_Assignment1.Models.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PRN222_Group2_Assignment1.Models.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PRN222_Group2_Assignment1.Models.AppUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Subject");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.DocumentChunk", b =>
                {
                    b.HasOne("PRN222_Group2_Assignment1.Models.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("PRN222_Group2_Assignment1.Models.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
